### ISSUE TITLE
[Feature]: Restructure input validation

### ISSUE THREAD

**Issue by ghost** [gchq/coreax#420]
### Describe the feature that you would like.*

Restructure how variables are validated throughout the codebase:

- Avoid explicit validation, instead passing variables to their point of use and letting an error be raised if the value is inappropriate at the point of use.
- If one of our functions does need to validate a variable in order to guard against security risks from bad input, use explicit `if` statements in preference to hidden validation functions, e.g. `if a < 5: raise ValueError("Suitable error message")` instead of `validate_in_range`.
- Remove the module `validation.py`.

### Why is this feature valuable to you?*

- Make the code easier to read.
- Reduce processing overhead for users who supply valid input.
- Guard against abuse of private functions.

### Additional context

The codebase currently includes various validation functions in validate.py. The core development team has agreed that these should be replaced using the approach described in this ticket.

### Code of Conduct*

- [x] I agree to follow this project's Code of Conduct

**Comment by tp832944** [comment]
Ticket needs to be broken down by module.

**Comment by tp832944** [comment]
Closing as covered by other, more granular tickets.

**Comment by tp832944** [comment]
@pc532627 Here is our strategy:

- Do cast when required, e.g. `jnp.atleast_2d`.
- Try to minimise the number of times the same thing is validated. This is easier said than done because we have many nested calls of public functions. In which case, we may just have to validate at point of use, rather than the `__init__` to classes.
- Keep `isinstance` (vanilla Python, not ours in `validation.py`) where necessary to provide useful error messages. If we're about to check for a particular attribute, it's probably not necessary to check the class is of the correct type.
- In `KernelHerding`, there's a double loop with `max_size` as the step parameter.
  - If positive, we're ok.
  - If zero, get unhelpful error.
  - If negative, fails silently with weird output as loop does not execute.
  - Define a function so that we can update `max_size` in a local scope.
  - `max_size = max(max_size, 0)`
  - `try: indices = range(from, to, max_size); except whatever error when step=0: raise ValueError("useful message")`
  - Only need to apply to one `range` as the other will yield the same error.
  - Key is a very tight `try-except` statement designed to only pick up exactly what we want to validate. Do not use an `if` statement in LBYL style if you can help it.
