### ISSUE TITLE
Partitioning in MapReduce

### ISSUE THREAD

**Issue by qh681248** [gchq/coreax#791]
### What's the issue?

Currently MapReduce is implemented such a way that if you partition a dataset into number of partitions that does not divide data then you would get partitions of unequal sizes, the current implementation repeats the last data point to fill the partitions, would it make more sense to use a random datapoint instead?

**Comment by tp832944** [comment]
A fixed value makes the algorithm more predictable. Would a null value not be better, with some kind of enforcement to ensure we never select it?

I used to know my way around the map reduce code, but it's been so long now that I'd have to upskill again to answer this one properly!

**Comment by tc85324** [comment]
Having taken a quick look, there appear to be a few problems with the map reduce solver (my apologies, it was somewhat rushed during the transition to the new solver API). The primary reason for padding with zero-valued and zero-weighted data points is explained in the comment at the top of `_jit_tree`:
```python

def _jit_tree(dataset: _Data, leaf_size: int, tree_type: type[BinaryTree]) -> _Data:
    """
    Return JIT compatible BinaryTree partitioning of 'dataset'.

    :param dataset: Input dataset from which the tree partitioning is generated
    :param leaf_size: Size of the partitions to generate; If 'leaf_size' is not an
        integer multiple of :code:`len(dataset)`, padding will be used to ensure all
        partitions have equal size.
    :param tree_type: The type of BinaryTree to use for partitioning.
    :return: The partitioned dataset
    """
    # To enable JIT compatibility, we must know the number of points per-leaf a priori.
    # Unfortunately, when the dataset size is not an integer power of two, the KDTree
    # may produce variable sized leaves where the number of points in each leaf obeys:
    # leaf_size <= n_points <= 2 * leaf_size
    # It is not obvious in this case if 'n_points' can be determined a priori.
    #
    # A simple solution is to pad the dataset with zero valued and weighted points, up
    # to the smallest integer power of two. An additional benefit of this padding is
    # that all partitions will be perfectly balanced (of identical size).
    #
    # IMPORTANT: the base solver should ignore/be invariant to these padding values;
    # ignorance is weaker condition than invariance. For example, due to implementation
    # details, the RandomSample solver will select different values when padding is
    # present, even though the probability of selecting these padded values is zero.
    # Thus the solver ignores the padded values, but the result is not invariant (it is
    # equivalent to selecting a different random key in this example)
```
In short, the logic is that padding should only exist to enable JIT compatibility; padding should not change the result of performing `MapReduce.reduce(...)`. E.G. given an array `x`, and a padded array `x_padded`, then `MapReduce.reduce(x) == MapReduce.reduce(x_padded)`.  

For any solver whose result changes due to  zero-valued and zero-weighted padding, I think the correct choice of padding is likely to be solver specific. What do you think?
